### ISSUE TITLE
Split CI and CD into separate GitHub Actions workflows

### ISSUE THREAD

**Issue by BrunoGrandePhD** [Sage-Bionetworks-Workflows/dockstore-tool-template#11]
(I'm still a novice when it comes to CI/CD, so this suggestion might be rooted in ignorance. Feel free to clarify any perceived misunderstanding.)

Currently the `ci.yaml` workflow gets triggered on all pushes to the `master` branch. It would be beneficial to test every PR on all repos deriving from this template. However, as stated in the `README.md`, it's not recommended to trigger `ci.yaml` on anything other than pushes to `master` for proper versioning. 

Would splitting CI (testing) and CD (versioning and deployment) into separate GitHub Actions workflows circumvent this issue? This way, we could test all pushes and PRs while separately versioning pushes to `master`.

**Comment by BrunoGrandePhD** [comment]
Currently, the `test` and `build` jobs are part of the same CI workflow (`ci.yaml`) because the deployment step (_i.e._ the `build` job) should only happen when the tests pass (_i.e._ the `test` job), hence the `needs:` dependency for `build`. This setup was kindly explained to me by @tthyer. 

Accordingly, these two jobs can't be separated, and it wouldn't be ideal if the `test` job was duplicated in another CI workflow that was run on all pushes and PRs. 

Would it be feasible for us to update the `ci.yaml` workflow to trigger on all pushes and PRs but restrict the `build` job therein to `github.ref == "refs/heads/master" by expanding the `if:` conditional (or something along these lines, as I'm not a GitHub Actions expert).

**Comment by tthyer** [comment]
@BrunoGrandePhD Good suggestion, let's do that.
